SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[DETAILRENTAL] (
		[RENT_NUM]                [numeric](8, 0) NOT NULL,
		[VID_NUM]                 [numeric](8, 0) NOT NULL,
		[DETAIL_FEE]              [numeric](5, 2) NULL,
		[DETAIL_DUEDATE]          [date] NULL,
		[DETAIL_RETURNDATE]       [date] NULL,
		[DETAIL_DAILYLATEFEE]     [numeric](5, 2) NULL,
		CONSTRAINT [DETAIL_RENT_VID_PK]
		PRIMARY KEY
		CLUSTERED
		([RENT_NUM], [VID_NUM])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETAILRENTAL] SET (LOCK_ESCALATION = TABLE)
GO
