SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MEMBERSHIP] (
		[MEM_NUM]         [numeric](8, 0) NOT NULL,
		[MEM_FNAME]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MEM_LNAME]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MEM_STREET]      [varchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MEM_CITY]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MEM_STATE]       [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MEM_ZIP]         [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MEM_BALANCE]     [numeric](10, 2) NULL,
		CONSTRAINT [PK__MEMBERSH__972E4E1DACA94F0A]
		PRIMARY KEY
		CLUSTERED
		([MEM_NUM])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEMBERSHIP] SET (LOCK_ESCALATION = TABLE)
GO
