SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RENTAL] (
		[RENT_NUM]      [numeric](8, 0) NULL,
		[RENT_DATE]     [date] NULL,
		[MEM_NUM]       [numeric](8, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RENTAL]
	WITH CHECK
	ADD CONSTRAINT [FK__RENTAL__MEM_NUM__300424B4]
	FOREIGN KEY ([MEM_NUM]) REFERENCES [dbo].[MEMBERSHIP] ([MEM_NUM])
ALTER TABLE [dbo].[RENTAL]
	CHECK CONSTRAINT [FK__RENTAL__MEM_NUM__300424B4]

GO
ALTER TABLE [dbo].[RENTAL] SET (LOCK_ESCALATION = TABLE)
GO
