SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[VIDEO] (
		[VID_NUM]        [numeric](8, 0) NOT NULL,
		[VID_INDATE]     [date] NULL,
		[MOVIE_NUM]      [numeric](8, 0) NULL,
		CONSTRAINT [PK__VIDEO__3A82860CD844CF52]
		PRIMARY KEY
		CLUSTERED
		([VID_NUM])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VIDEO]
	WITH CHECK
	ADD CONSTRAINT [FK__VIDEO__MOVIE_NUM__2C3393D0]
	FOREIGN KEY ([MOVIE_NUM]) REFERENCES [dbo].[MOVIE] ([MOVIE_NUM])
ALTER TABLE [dbo].[VIDEO]
	CHECK CONSTRAINT [FK__VIDEO__MOVIE_NUM__2C3393D0]

GO
ALTER TABLE [dbo].[VIDEO] SET (LOCK_ESCALATION = TABLE)
GO
