SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRICE] (
		[PRICE_CODE]             [numeric](2, 0) NOT NULL,
		[PRICE_DESCRIPTION]      [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRICE_RENTFEE]          [numeric](5, 2) NULL,
		[PRICE_DAILYLATEFEE]     [numeric](5, 2) NULL,
		CONSTRAINT [PK__PRICE__6AD6A3A3EC155171]
		PRIMARY KEY
		CLUSTERED
		([PRICE_CODE])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRICE]
	ADD
	CONSTRAINT [CK__PRICE__PRICE_REN__24927208]
	CHECK
	([PRICE_RENTFEE]>=(0))
GO
ALTER TABLE [dbo].[PRICE]
CHECK CONSTRAINT [CK__PRICE__PRICE_REN__24927208]
GO
ALTER TABLE [dbo].[PRICE]
	ADD
	CONSTRAINT [CK__PRICE__PRICE_DAI__25869641]
	CHECK
	([PRICE_DAILYLATEFEE]>=(0))
GO
ALTER TABLE [dbo].[PRICE]
CHECK CONSTRAINT [CK__PRICE__PRICE_DAI__25869641]
GO
ALTER TABLE [dbo].[PRICE] SET (LOCK_ESCALATION = TABLE)
GO
