SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MOVIE] (
		[MOVIE_NUM]       [numeric](8, 0) NOT NULL,
		[MOVIE_TITLE]     [varchar](75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MOVIE_YEAR]      [numeric](4, 0) NULL,
		[MOVIE_COST]      [numeric](5, 2) NULL,
		[MOVIE_GENRE]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PRICE_CODE]      [numeric](2, 0) NULL,
		CONSTRAINT [PK__MOVIE__896F539BD7EE6BC1]
		PRIMARY KEY
		CLUSTERED
		([MOVIE_NUM])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MOVIE]
	ADD
	CONSTRAINT [CK__MOVIE__MOVIE_YEA__286302EC]
	CHECK
	([MOVIE_YEAR]>(1900))
GO
ALTER TABLE [dbo].[MOVIE]
CHECK CONSTRAINT [CK__MOVIE__MOVIE_YEA__286302EC]
GO
ALTER TABLE [dbo].[MOVIE]
	WITH CHECK
	ADD CONSTRAINT [FK__MOVIE__PRICE_COD__29572725]
	FOREIGN KEY ([PRICE_CODE]) REFERENCES [dbo].[PRICE] ([PRICE_CODE])
ALTER TABLE [dbo].[MOVIE]
	CHECK CONSTRAINT [FK__MOVIE__PRICE_COD__29572725]

GO
ALTER TABLE [dbo].[MOVIE] SET (LOCK_ESCALATION = TABLE)
GO
